allowBuilds:
  esbuild: false
  msgpackr-extract: false
  workerd: false
minimumReleaseAgeExclude:
  - '@northguild/gmt@1.15.0'
overrides:
  '@effect/platform-bun': 4.0.0-rc.112
  '@effect/platform-node': 4.0.0-rc.112
  '@effect/platform-node-shared': 4.0.0-rc.112
  '@effect/sql-d1': 4.0.0-rc.112
  '@effect/sql-pg': 4.0.0-rc.112
  '@effect/vitest': 4.0.0-rc.112
  effect: 4.0.0-rc.112
